Feature/cax portal@cplp 200 bulk user creation - integration invitation service
tractusx-team-portal-onboarding/tractusx pull request #135
Opened 2022-02-24 17:31 UTC by evegufy

https://jira.catena-x.net/browse/CPLP-200 User Management - Users Bulk Upload (CX-IdP customers)
- implemented user creation endpoint in invitation service
- moved UserCreationInfo to Provisioning Library
- removed KeyCloakClientID from appsettings to be managed in secret
- set default realm for registration app to CX-Central

2022-02-24 22:10 UTC, ntruchsess requested changes

2022-02-24 22:10 UTC, ntruchsess commented on coreservices/invitation/src/CatenaX.NetworkServices.Invitation.Service/BusinessLogic/InvitationBusinessLogic.cs
> +            IOptionsSnapshot<InvitationSettings> settings)
please use IOptions instead of IOptionsSnapshot - there is no point in re-reading the settings with every instantiation of the service (settings retrieved via IOptions are read at startup once per application-instance).

2022-02-24 22:10 UTC, ntruchsess commented on coreservices/invitation/src/CatenaX.NetworkServices.Invitation.Service/BusinessLogic/InvitationBusinessLogic.cs
> +        public async Task<IEnumerable<string>> CreateUsersAsync(List<UserCreationInfo> usersToCreate, string tenant, string createdByEmail, string createdByName)
as no properties of List are actually being used rather use IEnumarable<..> instead of List<..>

2022-02-24 22:10 UTC, ntruchsess commented on coreservices/invitation/src/CatenaX.NetworkServices.Invitation.Service/Controllers/InvitationController.cs
> +                var createdByEmail = User.Claims.SingleOrDefault( x => x.Type=="preferred_username").Value as string;
This assumes users will always have the email-address mapped to the username. That is certainly the case for users that were just invited before but cannot be guaranteed for all times. If we need to access the email-address from the token we should reliably map it in the client config.

2022-02-24 22:10 UTC, ntruchsess commented on coreservices/invitation/src/CatenaX.NetworkServices.Invitation.Service/BusinessLogic/InvitationBusinessLogic.cs
> +                        { clientId, new []{user.Role}}
that allows anybody who has the portal-role 'add_user_account' to assign any(!) of the catanax-portal client roles to the newly created user (with no restrictions). Is this actually intended? That means that whoever has the role 'add_user_account' is more or less a full administator as he is free to create new administrative users. Is this actually intended? One cannot rely on the frontend to restict the roles that are allowed to be assigned without applying the same restriction in the backend (anything that is executed in the frontend is not trustworthy as a malicious user may just use postman).
I know this looks pretty much the same as in the registration-service - the main difference is that the catenax-registration client does not contain real administrative roles (and yes - there should be explicit restrictions being applied in the registration-service for the very same reason because the roles within the client may change in the future but nobody takes care to adjusting this line of code)

2022-02-24 22:10 UTC, ntruchsess commented on coreservices/invitation/src/CatenaX.NetworkServices.Invitation.Service/appsettings.json
> +      "KeyCloakClientID": "",
I cannot find where this value of KeyCloakClientID is actually being used? I can only see Portal.KeyCloakClientId being accessed.

2022-02-25 16:31 UTC, evegufy commented on coreservices/invitation/src/CatenaX.NetworkServices.Invitation.Service/appsettings.json
> +      "KeyCloakClientID": "",
Change is done.

2022-02-25 16:31 UTC, evegufy commented on coreservices/invitation/src/CatenaX.NetworkServices.Invitation.Service/BusinessLogic/InvitationBusinessLogic.cs
> +        public async Task<IEnumerable<string>> CreateUsersAsync(List<UserCreationInfo> usersToCreate, string tenant, string createdByEmail, string createdByName)
Change is done.

2022-02-25 16:31 UTC, evegufy commented on coreservices/invitation/src/CatenaX.NetworkServices.Invitation.Service/BusinessLogic/InvitationBusinessLogic.cs
> +                        { clientId, new []{user.Role}}
Will be addressed in follow up user stories.

2022-02-25 16:31 UTC, evegufy commented on coreservices/invitation/src/CatenaX.NetworkServices.Invitation.Service/Controllers/InvitationController.cs
> +                var createdByEmail = User.Claims.SingleOrDefault( x => x.Type=="preferred_username").Value as string;
Removed obsolete createdByEmail

2022-02-25 16:46 UTC, ntruchsess approved these changes

2022-02-25 16:46 UTC, ntruchsess commented on coreservices/invitation/src/CatenaX.NetworkServices.Invitation.Service/Controllers/InvitationController.cs
> +                {
diese beiden {} sind überflüssig

2022-02-25 16:49 UTC, ntruchsess commented
From my point of view ready to merge ;-)

2022-02-25 17:02 UTC, merged