Terms and condition link changes
tractusx-team-portal-onboarding/tractusx pull request #31
Opened 2021-10-28 11:29 UTC by vsamarora

Terms and condition link changes

2021-10-28 13:52 UTC, ntruchsess requested changes
see inline comments

2021-10-28 13:52 UTC, ntruchsess commented on portal/code/company-portal/src/components/termsncondition.tsx
> +      // private linkClick() {
please remove comments that are for debugging only

2021-10-28 13:52 UTC, ntruchsess commented on portal/code/tractus-x-portal/src/components/termsncondition.tsx
> +      // private linkClick() {
same here, please remove debugging-comment

2021-10-29 05:55 UTC, vsamarora commented on portal/code/company-portal/src/components/termsncondition.tsx
> +      // private linkClick() {
Removed

2021-10-29 05:55 UTC, vsamarora commented on portal/code/tractus-x-portal/src/components/termsncondition.tsx
> +      // private linkClick() {
removed

2021-10-29 07:03 UTC, ntruchsess approved these changes

2021-10-29 07:03 UTC, merged