Feature/cax portal@bpn service
tractusx-team-portal-onboarding/tractusx pull request #87
Opened 2022-01-31 12:28 UTC by TobiScw

Added bpn and custodian service

2022-01-31 12:31 UTC, nampacx approved these changes

2022-02-02 09:36 UTC, evegufy commented
@TobiScw could you please merge this PR? In the afternoon we'll merge our default branch in the main branch from the catenax tractusx repo, no PR should be open at that point.

2022-02-02 11:09 UTC, merged

2022-02-02 11:31 UTC, ntruchsess requested changes
see my inline comments

2022-02-02 11:31 UTC, ntruchsess commented on coreservices/registration/src/CatenaX.NetworkServices.Registration.Service/BPN/BPNAccess.cs
> +            var result = await _httpClient.GetAsync($"api/catena/businesspartners/{bpn}");
the bpn must be URL-encoded to ensure special characters (/,?,&...) are not misinterpreted by the api

2022-02-02 11:31 UTC, ntruchsess commented on coreservices/registration/src/CatenaX.NetworkServices.Registration.Service/BPN/BPNAccess.cs
> +                    var test = 5;
what is this good for?

2022-02-02 11:31 UTC, ntruchsess commented on coreservices/registration/src/CatenaX.NetworkServices.Registration.Service/BPN/BPNAccess.cs
> +            return response;
the method should propagate an appropriate exception in case the http-call was not successful

2022-02-02 11:31 UTC, ntruchsess commented on coreservices/registration/src/CatenaX.NetworkServices.Registration.Service/Controllers/RegistrationController.cs
> +                //if (!response.IsSuccessStatusCode)
why has this been removed?

2022-02-02 11:31 UTC, ntruchsess commented on coreservices/registration/src/CatenaX.NetworkServices.Registration.Service/Custodian/CustodianService.cs
> +            return response;
in case the request to the custodian api was unsuccessful the service should not result in http 200 ok but e.g. error 500

2022-02-02 11:31 UTC, ntruchsess commented on coreservices/registration/src/CatenaX.NetworkServices.Registration.Service/Custodian/CustodianService.cs
> +                throw new Exception("Token could not be retrieved");
Exception should be subclassed appropriately

2022-02-02 11:31 UTC, ntruchsess commented on coreservices/registration/src/CatenaX.NetworkServices.Registration.Service/Startup.cs
> +            services.AddHttpClient("bpn", c =>
creation of service-specific dependencies should be encapsulated like in class CustodianServiceCollectionExtension