Feature/cax potal@react bootstrap cplp344
tractusx-team-portal-onboarding/tractusx pull request #88
Opened 2022-01-31 13:13 UTC by vsamarora

API integration to fetch company data
API integration to submit company dat

2022-01-31 15:27 UTC, evegufy requested changes

2022-01-31 15:27 UTC, evegufy commented on portal/code/company-portal/src/components/cax-responsibilities.tsx
> +interface ISelectableOption<T = any> {
Instead of coping these interfaces from the old react library, we should refactor this file (and files with similar occurrences) to not depend on them.
For example. the availableUserRoles variable (line 50) can be changed to a string array.

2022-02-01 02:22 UTC, vsamarora commented on portal/code/company-portal/src/components/cax-responsibilities.tsx
> +interface ISelectableOption<T = any> {
updated changes

2022-02-01 09:44 UTC, evegufy commented on portal/code/company-portal/src/components/cax-companyData.tsx
> +interface ISelectableOption<T = any> {
Could the change from cax-responsibilities regarding these interfaces from the react library also be applied here?

2022-02-01 10:21 UTC, evegufy reviewed
Could the change from cax-responsibilities regarding these interfaces from the react library also be applied in cax-companyData?

2022-02-01 10:34 UTC, evegufy commented on portal/code/company-portal/src/components/cax-companyData.tsx
> +interface ISelectableOption<T = any> {
@vsamarora will raise another PR to address that.

2022-02-01 10:38 UTC, merged